[General]
background=/home/simon/Pictures/Wallpapers/f16c177ad884de53854ed09f451d8baf.jpg

# Override these per-machine if needed
font=JetBrainsMono Nerd Font
fontSize=10

# Accent colour pulled from hyprlock palette
accentColor=#87b8ff
