hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd([[sh -c 'command -v hyprpm >/dev/null && hyprpm reload -n']])
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd([[sh -c 'sleep 1; hyprctl hyprpaper wallpaper ",/home/simon/.config/hypr/current-wallpaper,cover"']])
    hl.exec_cmd("hypridle")
    hl.exec_cmd([[sh -c 'command -v nm-applet >/dev/null && nm-applet --indicator']])
    hl.exec_cmd([[sh -c 'command -v blueman-applet >/dev/null && blueman-applet']])
    hl.exec_cmd([[sh -c 'command -v wl-paste >/dev/null && wl-paste --type text --watch "$HOME/.config/hypr/scripts/clipboard-watch.sh" text']])
    hl.exec_cmd([[sh -c 'command -v wl-paste >/dev/null && wl-paste --type image --watch "$HOME/.config/hypr/scripts/clipboard-watch.sh" image']])
end)
